### ISSUE TITLE
Error in temperature raw->celsius calculation.

### ISSUE THREAD

**Issue by VaTTeRGeR** [STMicroelectronics/iis2mdc-pid#2]
There seems to be an error in the temperature conversion formula in [iis2mdc_reg.c](https://github.com/STMicroelectronics/iis2mdc-pid/blob/a58fe25466307011fe40e384278479a42fb20a1e/iis2mdc_reg.c#L100C8-L100C8).

I only get temperatures that vary slightly around 25°C, this is because there is an additional unnecessary divide by 16 in there. 

I fixed it like this:
```
float_t iis2mdc_from_lsb_to_celsius(int16_t lsb)
{
  /* 8 LSB/C - 12bit resolution */
  return ((((float_t)lsb) / 8.0f) + 25.0f);
}
```

You already have the correct version in the [stm32-iis2mdc](https://github.com/STMicroelectronics/stm32-iis2mdc/blob/f1b6d89d0aa1f83fa2c9c2a34161c3900a9c77ad/iis2mdc_reg.c#L98) version of this driver.

I would urge you to also add this small fix here too, this might trip up some unsuspecting people.

**Comment by avisconti** [comment]
Actually if you see I have introduced this change here (Nov 9th): 4230507
Before it was like your change

So, are you saying that I have to revert that commit? But I really need to shift the value 4 position on the left, why did you remove the ```/16``` division?

**Comment by VaTTeRGeR** [comment]
Why did you introduce the additional divide by 16 in the first place?

The 16-bit signed value in the TEMP_OUT_L_REG and TEMP_OUT_H_REG register is already a correctly formatted 16-bit signed integer, since the 4 "unused" most significant bits are correctly filled with the sign bit:
![grafik](https://github.com/STMicroelectronics/iis2mdc-pid/assets/5089550/e8c29d7d-774b-4da8-a293-ee1451c03683)

Maybe the raw value is read incorrectly on some platforms? I noticed that the way that the 16-bit signed value is assembled from two unsigned bytes, is expressed by a multiplication in [iis2mdc_temperature_raw_get(...)](https://github.com/STMicroelectronics/iis2mdc-pid/blob/a58fe25466307011fe40e384278479a42fb20a1e/iis2mdc_reg.c#L699C15-L699C15):
```
int32_t iis2mdc_temperature_raw_get(stmdev_ctx_t *ctx, int16_t *val)
{
  uint8_t buff[2];
  int32_t ret;

  ret =  iis2mdc_read_reg(ctx, IIS2MDC_TEMP_OUT_L_REG, buff, 2);
  *val = (int16_t)buff[1];
  *val = (*val * 256) + (int16_t)buff[0];

  return ret;
}
```

Isn't it more unambigous, for the compiler and the readers of the code, to use a proper mask-shift operation for this purpose? 

Like this:
```
int32_t iis2mdc_temperature_raw_get(stmdev_ctx_t *ctx, int16_t *val)
{
  uint8_t buff[2];
  int32_t ret;

  ret =  iis2mdc_read_reg(ctx, IIS2MDC_TEMP_OUT_L_REG, buff, 2);
  *val = (int16_t)( ( ( buff[1] & 0xFF ) << 8 ) | ( ( buff[0] & 0xFF ) << 0 ) );

  return ret;
}
```
(Unnecessary shifts/masks will get optimized out by the compiler, i kept them for consistency.)

Anyway, after removing the divide by 16, my temperature measurements are in line with the other close-by temperature sensors on my pcb. Without the fix, the IIS2s temperature readings will stay near ~25°C, while the other sensors all consistently read higher values when heating the board.

Adding the mask-shift fix did not change my results btw, but it could be the reason you had problems, if your compiler interprets this in a different way.

I tested it by heating up the entire board with a heat gun and observing the values rise and fall. The board has a large ground plane with lots of vias, so this isn't some local variance in readings.

**Comment by avisconti** [comment]
> Why did you introduce the additional divide by 16 in the first place?
> 

I fixed an issue on lis2hh12, and I applied by mistake same commit on iis2mdc and lis2mdl, because it seemed to me that they were 8bit but left aligned.

> The 16-bit signed value in the TEMP_OUT_L_REG and TEMP_OUT_H_REG register is already a correctly formatted 16-bit signed integer, since the 4 "unused" most significant bits are correctly filled with the sign bit: ![grafik](https://private-user-images.githubusercontent.com/5089550/293895807-e8c29d7d-774b-4da8-a293-ee1451c03683.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyODQyMTEsIm5iZiI6MTcwNDI4MzkxMSwicGF0aCI6Ii81MDg5NTUwLzI5Mzg5NTgwNy1lOGMyOWQ3ZC03NzRiLTRkYTgtYTI5My1lZTE0NTFjMDM2ODMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDNUMTIxMTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Nzg0ZTg0MjY4MjRhM2U2MGExY2JmNzYyNTQzNmY2NzI0NDAyODNmZjgzNmZhNjVmY2E2N2FmMDczZTQzN2QzNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OyRakw3RrmsActyM9PA5wfm8YqsmKm0g1pgvFuexDCw)
> 


Ok, I see. I didn't read it carefully. Sorry for that.

> Maybe the raw value is read incorrectly on some platforms? I noticed that the way that the 16-bit signed value is assembled from two unsigned bytes, is expressed by a multiplication in [iis2mdc_temperature_raw_get(...)](https://github.com/STMicroelectronics/iis2mdc-pid/blob/a58fe25466307011fe40e384278479a42fb20a1e/iis2mdc_reg.c#L699C15-L699C15):
> 
> ```
> int32_t iis2mdc_temperature_raw_get(stmdev_ctx_t *ctx, int16_t *val)
> {
>   uint8_t buff[2];
>   int32_t ret;
> 
>   ret =  iis2mdc_read_reg(ctx, IIS2MDC_TEMP_OUT_L_REG, buff, 2);
>   *val = (int16_t)buff[1];
>   *val = (*val * 256) + (int16_t)buff[0];
> 
>   return ret;
> }
> ```
> 
> Isn't it more unambigous, for the compiler and the readers of the code, to use a proper mask-shift operation for this purpose?
> 
> Like this:
> 
> ```
> int32_t iis2mdc_temperature_raw_get(stmdev_ctx_t *ctx, int16_t *val)
> {
>   uint8_t buff[2];
>   int32_t ret;
> 
>   ret =  iis2mdc_read_reg(ctx, IIS2MDC_TEMP_OUT_L_REG, buff, 2);
>   *val = (int16_t)( ( ( buff[1] & 0xFF ) << 8 ) | ( ( buff[0] & 0xFF ) << 0 ) );
> 
>   return ret;
> }
> ```
> 
> (Unnecessary shifts/masks will get optimized out by the compiler, i kept them for consistency.)
> 

Yes, I think the two notations are equivalent. Nevertheless, I'll think about it more.

> Anyway, after removing the divide by 16, my temperature measurements are in line with the other close-by temperature sensors on my pcb. Without the fix, the IIS2s temperature readings will stay near ~25°C, while the other sensors all consistently read higher values when heating the board.
> 
> Adding the mask-shift fix did not change my results btw, but it could be the reason you had problems, if your compiler interprets this in a different way.
> 
> I tested it by heating up the entire board with a heat gun and observing the values rise and fall. The board has a large ground plane with lots of vias, so this isn't some local variance in readings.

Ok, good.

**Comment by avisconti** [comment]
commit reverted
